version: '3'

services:
  checkers:
    build: .
    ports:
      - "5050:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=Checkers.py
    command: gunicorn --bind 0.0.0.0:8080 Checkers:app
