version: '3'

services:
  checkers:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=Checkers.py
    command: gunicorn --bind 0.0.0.0:8080 --log-level debug Checkers:app
