version: '3'

services:
  checkers:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    environment:
      - FLASK_ENV=production
      - FLASK_APP=Checkers.py
    command: gunicorn --bind 0.0.0.0:8080 Checkers:app
